# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.20.00, with svd2pac 0.4.0 on Sat, 12 Apr 2025 22:16:54 +0000

[package]
name = "ra6e1-pac"
version = "0.0.1"
edition = "2021"
description = "Peripheral Access Crate (PAC) for R7FAA6E1."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra6e1", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra6e1-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license = "LICENSE.TXT"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
rmpu = []
tzf = []
sram = []
bus = []
dmac0 = []
dmac1 = [ "dmac0" ]
dmac2 = [ "dmac0" ]
dmac3 = [ "dmac0" ]
dmac4 = [ "dmac0" ]
dmac5 = [ "dmac0" ]
dmac6 = [ "dmac0" ]
dmac7 = [ "dmac0" ]
dma = []
dtc = []
icu = []
cache = []
cpscu = []
dbg = []
fcache = []
sysc = []
port0 = []
port1 = []
port2 = [ "port1" ]
port3 = [ "port1" ]
port4 = [ "port1" ]
port5 = [ "port0" ]
port6 = [ "port0" ]
port7 = [ "port0" ]
port8 = [ "port0" ]
pfs = []
elc = []
rtc = []
iwdt = []
wdt = []
cac = []
mstp = []
poeg = []
usbfs = []
sdhi0 = []
ssie0 = []
iic0 = []
iic0wu = []
iic1 = [ "iic0" ]
can0 = []
pscu = []
agt0 = []
agt1 = [ "agt0" ]
agt2 = [ "agt0" ]
agt3 = [ "agt0" ]
agt4 = [ "agt0" ]
agt5 = [ "agt0" ]
crc = []
doc = []
edmac0 = []
etherc0 = []
sci0 = []
sci1 = []
sci2 = []
sci3 = []
sci4 = [ "sci3" ]
sci9 = [ "sci0" ]
spi0 = []
spi1 = [ "spi0" ]
gpt321 = []
gpt322 = [ "gpt321" ]
gpt164 = []
gpt165 = [ "gpt164" ]
gpt166 = [ "gpt164" ]
gpt167 = [ "gpt164" ]
adc120 = []
dac12 = []
flad = []
faci = []
qspi = []

all = ["rmpu" ,"tzf" ,"sram" ,"bus" ,"dmac0" ,"dmac1" ,"dmac2" ,"dmac3" ,"dmac4" ,"dmac5" ,"dmac6" ,"dmac7" ,"dma" ,"dtc" ,"icu" ,"cache" ,"cpscu" ,"dbg" ,"fcache" ,"sysc" ,"port0" ,"port1" ,"port2" ,"port3" ,"port4" ,"port5" ,"port6" ,"port7" ,"port8" ,"pfs" ,"elc" ,"rtc" ,"iwdt" ,"wdt" ,"cac" ,"mstp" ,"poeg" ,"usbfs" ,"sdhi0" ,"ssie0" ,"iic0" ,"iic0wu" ,"iic1" ,"can0" ,"pscu" ,"agt0" ,"agt1" ,"agt2" ,"agt3" ,"agt4" ,"agt5" ,"crc" ,"doc" ,"edmac0" ,"etherc0" ,"sci0" ,"sci1" ,"sci2" ,"sci3" ,"sci4" ,"sci9" ,"spi0" ,"spi1" ,"gpt321" ,"gpt322" ,"gpt164" ,"gpt165" ,"gpt166" ,"gpt167" ,"adc120" ,"dac12" ,"flad" ,"faci" ,"qspi"]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all","rt"]
