# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.40.00, with svd2pac 0.4.0 on Sat, 12 Apr 2025 22:18:35 +0000

[package]
name = "ra6t2-pac"
version = "0.0.1"
edition = "2021"
description = "Peripheral Access Crate (PAC) for R7FAA6T2."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra6t2", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra6t2-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license = "LICENSE.TXT"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
rmpu = []
tzf = []
sram = []
bus = []
dmac0 = []
dmac1 = [ "dmac0" ]
dmac2 = [ "dmac0" ]
dmac3 = [ "dmac0" ]
dmac4 = [ "dmac0" ]
dmac5 = [ "dmac0" ]
dmac6 = [ "dmac0" ]
dmac7 = [ "dmac0" ]
dma = []
dtc = []
icu = []
cache = []
cpscu = []
dbg = []
fcache = []
sysc = []
port0 = []
port2 = []
porta = []
portb = []
portc = []
portd = []
porte = []
pfs_b = []
iirfa = []
tfu = []
elc_b = []
iwdt = []
wdt = []
cac = []
mstp = []
kint = []
poeg = []
canfd = []
pscu = []
agtw_b0 = []
agtw_b1 = [ "agtw_b0" ]
tsn = []
acmphs0 = []
acmphs1 = [ "acmphs0" ]
acmphs2 = [ "acmphs0" ]
acmphs3 = [ "acmphs0" ]
crc = []
doc_b = []
sci_b0 = []
sci_b1 = [ "sci_b0" ]
sci_b2 = [ "sci_b0" ]
sci_b3 = [ "sci_b0" ]
sci_b4 = [ "sci_b0" ]
sci_b9 = [ "sci_b0" ]
spi_b0 = []
spi_b1 = [ "spi_b0" ]
iic_b0 = []
iic0wu_b = []
iic_b1 = [ "iic_b0" ]
eccmb = []
gpt320 = []
gpt321 = [ "gpt320" ]
gpt322 = [ "gpt320" ]
gpt323 = [ "gpt320" ]
gpt324 = []
gpt325 = [ "gpt324" ]
gpt326 = [ "gpt324" ]
gpt327 = [ "gpt324" ]
gpt328 = [ "gpt324" ]
gpt329 = [ "gpt324" ]
gpt_ops = []
gpt_gtclk = []
pdg = []
adc_b = []
dac120 = []
dac121 = [ "dac120" ]
tsd = []
flad = []
faci = []

all = ["rmpu" ,"tzf" ,"sram" ,"bus" ,"dmac0" ,"dmac1" ,"dmac2" ,"dmac3" ,"dmac4" ,"dmac5" ,"dmac6" ,"dmac7" ,"dma" ,"dtc" ,"icu" ,"cache" ,"cpscu" ,"dbg" ,"fcache" ,"sysc" ,"port0" ,"port2" ,"porta" ,"portb" ,"portc" ,"portd" ,"porte" ,"pfs_b" ,"iirfa" ,"tfu" ,"elc_b" ,"iwdt" ,"wdt" ,"cac" ,"mstp" ,"kint" ,"poeg" ,"canfd" ,"pscu" ,"agtw_b0" ,"agtw_b1" ,"tsn" ,"acmphs0" ,"acmphs1" ,"acmphs2" ,"acmphs3" ,"crc" ,"doc_b" ,"sci_b0" ,"sci_b1" ,"sci_b2" ,"sci_b3" ,"sci_b4" ,"sci_b9" ,"spi_b0" ,"spi_b1" ,"iic_b0" ,"iic0wu_b" ,"iic_b1" ,"eccmb" ,"gpt320" ,"gpt321" ,"gpt322" ,"gpt323" ,"gpt324" ,"gpt325" ,"gpt326" ,"gpt327" ,"gpt328" ,"gpt329" ,"gpt_ops" ,"gpt_gtclk" ,"pdg" ,"adc_b" ,"dac120" ,"dac121" ,"tsd" ,"flad" ,"faci"]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all","rt"]
