# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.2, with svd2pac 0.4.0 on Sat, 12 Apr 2025 22:15:57 +0000

[package]
name = "ra4m1-pac"
version = "0.0.1"
edition = "2021"
description = "Peripheral Access Crate (PAC) for R7FAA4M1."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra4m1", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra4m1-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license = "LICENSE.TXT"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
system = []
bus = []
cac = []
can0 = []
dbg = []
crc = []
ctsu = []
dac12 = []
dac8 = []
dmac0 = []
dmac1 = [ "dmac0" ]
dmac2 = [ "dmac0" ]
dmac3 = [ "dmac0" ]
dma = []
doc = []
dtc = []
elc = []
fcache = []
port0 = []
port1 = []
port2 = [ "port1" ]
port3 = [ "port1" ]
port4 = [ "port1" ]
port5 = [ "port0" ]
port6 = [ "port0" ]
port7 = [ "port0" ]
port8 = [ "port0" ]
port9 = [ "port0" ]
pfs = []
pmisc = []
icu = []
iic0 = []
iic1 = []
iwdt = []
kint = []
mstp = []
mmpu = []
smpu = []
spmon = []
opamp = []
poeg = []
sram = []
rtc = []
sci0 = []
sci1 = [ "sci0" ]
sci2 = []
sci9 = [ "sci2" ]
slcdc = []
spi0 = []
spi1 = []
ssie0 = []
tsn = []
usbfs = []
wdt = []
acmplp = []
adc140 = []
agt0 = []
agt1 = [ "agt0" ]
gpt320 = []
gpt321 = [ "gpt320" ]
gpt162 = []
gpt163 = [ "gpt162" ]
gpt164 = [ "gpt162" ]
gpt165 = [ "gpt162" ]
gpt166 = [ "gpt162" ]
gpt167 = [ "gpt162" ]
gpt_ops = []

all = ["system" ,"bus" ,"cac" ,"can0" ,"dbg" ,"crc" ,"ctsu" ,"dac12" ,"dac8" ,"dmac0" ,"dmac1" ,"dmac2" ,"dmac3" ,"dma" ,"doc" ,"dtc" ,"elc" ,"fcache" ,"port0" ,"port1" ,"port2" ,"port3" ,"port4" ,"port5" ,"port6" ,"port7" ,"port8" ,"port9" ,"pfs" ,"pmisc" ,"icu" ,"iic0" ,"iic1" ,"iwdt" ,"kint" ,"mstp" ,"mmpu" ,"smpu" ,"spmon" ,"opamp" ,"poeg" ,"sram" ,"rtc" ,"sci0" ,"sci1" ,"sci2" ,"sci9" ,"slcdc" ,"spi0" ,"spi1" ,"ssie0" ,"tsn" ,"usbfs" ,"wdt" ,"acmplp" ,"adc140" ,"agt0" ,"agt1" ,"gpt320" ,"gpt321" ,"gpt162" ,"gpt163" ,"gpt164" ,"gpt165" ,"gpt166" ,"gpt167" ,"gpt_ops"]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all","rt"]
