# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.1, with svd2pac 0.4.0 on Sat, 12 Apr 2025 22:14:39 +0000

[package]
name = "ra2a1-pac"
version = "0.0.1"
edition = "2021"
description = "Peripheral Access Crate (PAC) for R7FAA2A1."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra2a1", "ra", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/ra-pac"
documentation = "https://docs.rs/crate/ra2a1-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license = "LICENSE.TXT"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.11", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
acmphs0 = []
acmplp = []
adc160 = []
ctsu = []
opamp = []
sdadc24 = []
tsn = []
dac12 = []
dac8 = []
elc = []
iwdt = []
kint = []
usbfs = []
wdt = []
cac = []
crc = []
doc = []
sci0 = []
sci1 = []
sci9 = [ "sci1" ]
spi0 = []
spi1 = [ "spi0" ]
can0 = []
iic0 = []
iic1 = []
mmf = []
mmpu = []
smpu = []
spmon = []
sram = []
bus = []
dbg = []
dtc = []
icu = []
system = []
mstp = []
agt0 = []
agt1 = [ "agt0" ]
gpt320 = []
gpt_ops = []
gpt161 = []
gpt162 = [ "gpt161" ]
gpt163 = [ "gpt161" ]
gpt164 = [ "gpt161" ]
gpt165 = [ "gpt161" ]
gpt166 = [ "gpt161" ]
poeg = []
rtc = []
fcache = []
port0 = []
port1 = []
port2 = [ "port1" ]
port3 = [ "port0" ]
port4 = [ "port0" ]
port5 = [ "port0" ]
port9 = [ "port0" ]
pfs = []
pmisc = []

all = ["acmphs0" ,"acmplp" ,"adc160" ,"ctsu" ,"opamp" ,"sdadc24" ,"tsn" ,"dac12" ,"dac8" ,"elc" ,"iwdt" ,"kint" ,"usbfs" ,"wdt" ,"cac" ,"crc" ,"doc" ,"sci0" ,"sci1" ,"sci9" ,"spi0" ,"spi1" ,"can0" ,"iic0" ,"iic1" ,"mmf" ,"mmpu" ,"smpu" ,"spmon" ,"sram" ,"bus" ,"dbg" ,"dtc" ,"icu" ,"system" ,"mstp" ,"agt0" ,"agt1" ,"gpt320" ,"gpt_ops" ,"gpt161" ,"gpt162" ,"gpt163" ,"gpt164" ,"gpt165" ,"gpt166" ,"poeg" ,"rtc" ,"fcache" ,"port0" ,"port1" ,"port2" ,"port3" ,"port4" ,"port5" ,"port9" ,"pfs" ,"pmisc"]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all","rt"]
